# Generated by Django 5.1.6 on 2025-03-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_curso_nivel_alter_matricula_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='periodo',
            field=models.CharField(choices=[('N', 'Noturno'), ('M', 'Matutino'), ('V', 'Vespertino')], default='M', max_length=1),
        ),
    ]
